cicd:Fix pull request approved #TASK-5564

diff --git a/.github/workflows/pull-request-approved.yml b/.github/workflows/pull-request-approved.yml
--- a/.github/workflows/pull-request-approved.yml
+++ b/.github/workflows/pull-request-approved.yml
@@ -25,7 +25,15 @@ jobs:
           chmod +x ./.github/workflows/scripts/get-xetabase-branch.sh
           echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
           echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
-          xetabase_branch=$(./.github/workflows/scripts/get-xetabase-branch.sh ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }})
+          set +e  # Desactivar exit on error temporalmente
+          xetabase_branch=$(./.github/workflows/scripts/get-xetabase-branch.sh ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }} 2>&1)
+          exit_code=$?
+          set -e
+          if [ $exit_code -ne 0 ]; then
+            echo "::error::Script failed with exit code $exit_code"
+            echo "Output: $xetabase_branch"
+            exit $exit_code
+          fi
           echo "__Xetabase ref:__ \"${xetabase_branch}\"" | tee -a ${GITHUB_STEP_SUMMARY}
           echo "xetabase_branch: ${xetabase_branch}"
           echo "xetabase_branch=${xetabase_branch}" >> $GITHUB_OUTPUT
